version: "3.1"
services:

  stormy_mysql:
    build: d-mysql
    volumes:
      - "stormy_mysql_data:/var/lib/mysql"
      - "./krash.mysql.cnf:/etc/mysql/conf.d/krash.mysql.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=REPLACEME
    labels:
      - com.charlesreid1.pod.name="mysql"

  stormy_myadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "8080:80"
    links:
      - stormy_mysql:db
    labels:
      - com.charlesreid1.pod.name="phpmyadmin"

  stormy_mw:
    build: d-mediawiki
    volumes:
      - "stormy_mw_data:/var/www/html"
    ports:
      - "80:80"
    links:
      - stormy_mysql:mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=wikidb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=REPLACEME
    labels:
      - com.charlesreid1.pod.name="mw"

volumes:
  stormy_mysql_data:
    external:
      name: stormy_mysql_data
  stormy_mw_data:
    external:
      name: stormy_mw_data
#secrets:
#  mysql_root_password:
#    file: ./root.password
