version: "3.1"
services:

  stormy_gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - "stormy_gitea_data:/data"
      - "./d-gitea/app.ini:/data/gitea/conf/app.ini"
    ports:
      - "222:22"
      #- "3000:3000"

  stormy_mysql:
    build: d-mysql
    volumes:
      - "stormy_mysql_data:/var/lib/mysql"
      #- "./d-mysql/krash.mysql.cnf:/etc/mysql/conf.d/krash.mysql.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=REPLACEME
    labels:
      - com.charlesreid1.pod.name="mysql"

  stormy_myadmin:
    image: "phpmyadmin/phpmyadmin"
    links:
      - stormy_mysql:db
    labels:
      - com.charlesreid1.pod.name="phpmyadmin"
    environment:
      - PMA_ABSOLUTE_URI=charlesreid1.blue/phpMyAdmin

  stormy_mw:
    build: d-mediawiki
    volumes:
      - "stormy_mw_data:/var/www/html"
    links:
      - stormy_mysql:mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=wikidb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=REPLACEME
    labels:
      - com.charlesreid1.pod.name="mw"

  stormy_nginx:
    restart: always
    image: nginx
    hostname: charlesreid1.blue
    command: /bin/bash -c "nginx -g 'daemon off;'"
    links:
      - stormy_gitea:stormy_gitea
      - stormy_mw:stormy_mw
      - stormy_myadmin:stormy_myadmin
    volumes:
      - "./d-nginx-charlesreid1/conf.d:/etc/nginx/conf.d"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/www/charlesreid1.blue/htdocs:/www/charlesreid1.blue/htdocs:ro"
      - "/www/charlesreid1.red/htdocs:/www/charlesreid1.red/htdocs:ro"
    ports:
      - "80:80"
      - "443:443"

volumes:
  stormy_mysql_data:
  stormy_mw_data:
  stormy_gitea_data:
