version: '2'
services:

  stormy_mysql:
    build: ../d-mysql
    volumes:
      - stormy_mysql_data:/var/lib/mysql
      - krash.mysql.cnf:/etc/mysql/conf.d/krash.mysql.cnf
    environment:
      - MYSQL_ROOT_PASSWORD: example
    labels:
      - com.charlesreid1.pod.name: "stormy_mysql"
      - com.charlesreid1.pod.bin: "mysql"

  stormy_myadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "8080:80"
    links:
      - stormy_mysql:db
    secrets:
      - mysql_root_password
    labels:
      - com.charlesreid1.pod.name: "stormy_mysql"
      - com.charlesreid1.pod.bin: "mysql"



volumes:
  stormy_mysql_data:
    exernal:
      name: stormy_mysql_data

secrets:
  mysql_root_password:
    file: ./root.password
