version: "3.1"
services:

  stormy_mysql:
    build: d-mysql
    volumes:
      - "stormy_mysql_data:/var/lib/mysql"
      - "./krash.mysql.cnf:/etc/mysql/conf.d/krash.mysql.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=example
    secrets:
      - mysql_root_password
    labels:
      - com.charlesreid1.pod.name="stormy_mysql"
      - com.charlesreid1.pod.bin="mysql"

  stormy_myadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "8080:80"
    links:
      - stormy_mysql:db
    labels:
      - com.charlesreid1.pod.name="stormy_mysql"
      - com.charlesreid1.pod.bin="mysql"

  stormy_mw:
    build: d-mediawiki
    volumes:
      - "stormy_mw_data:/var/www/html"
    ports:
      - "80:80"
    links:
      - stormy_mysql:mysql
    environment:
      - MEDIAWIKI_SITE_SERVER=45.56.87.232
      - MEDIAWIKI_DB_HOST=mysql
      - MEDIAWIKI_DB_NAME=wikidb
      - MEDIAWIKI_DB_USER=root
      - MEDIAWIKI_DB_PASSWORD=example

volumes:
  stormy_mysql_data:
    external:
      name: stormy_mysql_data
  stormy_mw_data:
    external:
      name: stormy_mw_data
secrets:
  mysql_root_password:
    file: ./root.password
