site_name: pod-charlesreid1
site_url: https://pages.charlesreid1.com/pod-charlesreid1
repo_name: d-charlesreid1
repo_url: https://git.charlesreid1.com/docker/d-charlesreid1
edit_uri: ""

copyright: 'Copyright &copy; 2018 <a href="https://charlesreid1.com">Charles Reid</a>'

docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'blue'
    accent: 'blue'
  logo:
    icon: 'dns'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
pages:
  - 'Index' : 'index.md'
  - 'Running the Charlesreid1 Docker Pod' : 'Running.md'
  - 'Volumes' : 'Volumes.md'
  - 'Backups (TODO)' : 'Backups.md'
  - 'Domains and Ports' : 'Ports.md'
  - 'Secrets' : 'Secrets.md'
  - 'Pod Service: MediaWiki' : 'Service_mediawiki.md'
  - 'Pod Service: Apache/PHP' : 'Service_apachephp.md'
  - 'Pod Service: MySQL' : 'Service_mysql.md'
  - 'Pod Service: phpMyAdmin' : 'Service_phpmyadmin.md'
  - 'Pod Service: nginx' : 'Service_nginx.md'
  - 'Pod Service: Python File Server' : 'Service_pythonfiles.md'
  - 'Pod Service: Gitea' : 'Service_gitea.md'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
